### ISSUE TITLE
Bug: worker tip percentage - "NAN"

### ISSUE THREAD

**Issue by NessKotenko** [IliaKamilov/smart-tip#13]
When inserting a workers tip percentage (תשר),
There is an unintended option to have 2 (or more than one) decimal points.
 when someone inputs inside the tip percentage field ("50.5.5") - a popped up error messages appears ("NAN"),
On every calulated and result tables.

![Screenshot_20210705-114840_Chrome](https://user-images.githubusercontent.com/1732754/124446169-dabc5b00-dd88-11eb-80bc-1ed08ea2206c.jpg)

![Screenshot_20210705-114851_Chrome](https://user-images.githubusercontent.com/1732754/124446127-cf692f80-dd88-11eb-9228-55440e7bcabb.jpg)

**Comment by IliaKamilov** [comment]
Thank you for the reply.
I will fix it soon!

**Comment by IliaKamilov** [comment]
Bug fix - beta 1.2.2:
- Number pad will allow only one appeareance of dot.
